[package]
name = "autocleaner"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
rfd = "0.13"
chrono = "0.4"
walkdir = "2.4"

[[bin]]
name = "autocleaner"
path = "src/main.rs"
